baseurl = "https://debruine.github.io"
title = "Lisa DeBruine"

theme = "hugo-coder"

languagecode = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "https-debruine-github-io"

enableEmoji = true

highlightjsVersion = "9.11.0"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml"]
highlightjsTheme = "github"

MathJaxCDN = "//cdn.bootcss.com"
MathJaxVersion = "2.7.1"

[params]
    author = "Lisa DeBruine"
    description = "Lisa DeBruine's coding website"
    keywords = "blog,code"
    info = "Rstats & Code & Stuff"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "2006-01-02"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    #commit = "https://github.com/lisadebruine/debruine.github.io/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = ["/css/xcode.css", "/css/style.css", "https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/debruine/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/lisadebruine/"
[[params.social]]
    name = "OSF"
    icon = "ai ai-osf"
    weight = 3
    url = "https://osf.io/4i578/"
[[params.social]]
    name = "FigShare"
    icon = "ai ai-figshare"
    weight = 4
    url = "https://figshare.com/authors/Lisa_DeBruine/3235773"
[[params.social]]
    name = "ORCiD"
    icon = "ai ai-orcid"
    weight = 5
    url = "http://orcid.org/0000-0002-7523-5539"
[[params.social]]
    name = "Google Scholar"
    icon = "ai ai-google-scholar"
    weight = 6
    url = "https://scholar.google.co.uk/citations?hl=en&pli=1&user=oLHcVYUAAAAJ"
[[params.social]]
    name = "email"
    icon = "far fa-paper-plane"
    weight = 7
    url = "mailto:lisa.debruine@glasgow.ac.uk"
    
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "About"
    weight = 3
    url = "/about/"

